-- MySQL Script generated by MySQL Workbench
-- jue 15 abr 2021 10:54:01 CST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema inspecciones_barva
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `inspecciones_barva` ;

-- -----------------------------------------------------
-- Schema inspecciones_barva
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `inspecciones_barva` DEFAULT CHARACTER SET ujis ;
USE `inspecciones_barva` ;

-- -----------------------------------------------------
-- Table `inspecciones_barva`.`actividad`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `inspecciones_barva`.`actividad` ;

CREATE TABLE IF NOT EXISTS `inspecciones_barva`.`actividad` (
  `PK_Codigo` INT NOT NULL,
  `Descripcion` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`PK_Codigo`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = ujis;


-- -----------------------------------------------------
-- Table `inspecciones_barva`.`rol`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `inspecciones_barva`.`rol` ;

CREATE TABLE IF NOT EXISTS `inspecciones_barva`.`rol` (
  `FK_Codigo` INT NOT NULL,
  `Descripcion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`FK_Codigo`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = ujis;


-- -----------------------------------------------------
-- Table `inspecciones_barva`.`usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `inspecciones_barva`.`usuario` ;

CREATE TABLE IF NOT EXISTS `inspecciones_barva`.`usuario` (
  `PK_ID` VARCHAR(45) NOT NULL,
  `Tipo` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`PK_ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = ujis;


-- -----------------------------------------------------
-- Table `inspecciones_barva`.`tipo identificacion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `inspecciones_barva`.`tipo identificacion` ;

CREATE TABLE IF NOT EXISTS `inspecciones_barva`.`tipo identificacion` (
  `Codigo` INT NOT NULL,
  `Descripcion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Codigo`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = ujis;


-- -----------------------------------------------------
-- Table `inspecciones_barva`.`administrativo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `inspecciones_barva`.`administrativo` ;

CREATE TABLE IF NOT EXISTS `inspecciones_barva`.`administrativo` (
  `PK_ID` VARCHAR(45) NOT NULL,
  `Nombre` VARCHAR(45) NULL DEFAULT NULL,
  `FK_Rol` INT NOT NULL,
  `Correo` VARCHAR(45) NULL DEFAULT NULL,
  `Clave` VARCHAR(100) NULL DEFAULT NULL,
  `Tipo_Identificacion` INT NULL DEFAULT NULL,
  PRIMARY KEY (`PK_ID`),
  INDEX `fk_Administrativo_Usuario1_idx` (`PK_ID` ASC) VISIBLE,
  INDEX `fk_Administrativo_Rol1_idx` (`FK_Rol` ASC) VISIBLE,
  INDEX `fk_Tipo_Identificacion` (`Tipo_Identificacion` ASC) VISIBLE,
  CONSTRAINT `fk_Administrativo_Rol1`
    FOREIGN KEY (`FK_Rol`)
    REFERENCES `inspecciones_barva`.`rol` (`FK_Codigo`),
  CONSTRAINT `fk_Administrativo_Usuario1`
    FOREIGN KEY (`PK_ID`)
    REFERENCES `inspecciones_barva`.`usuario` (`PK_ID`),
  CONSTRAINT `fk_Tipo_Identificacion`
    FOREIGN KEY (`Tipo_Identificacion`)
    REFERENCES `inspecciones_barva`.`tipo identificacion` (`Codigo`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = ujis;


-- -----------------------------------------------------
-- Table `inspecciones_barva`.`comercial`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `inspecciones_barva`.`comercial` ;

CREATE TABLE IF NOT EXISTS `inspecciones_barva`.`comercial` (
  `FK_Actividad` INT NOT NULL,
  `Nombre_Local` VARCHAR(45) NULL DEFAULT NULL,
  `Patente` TINYINT NULL DEFAULT NULL,
  INDEX `fk_Comercial_Actividad2_idx` (`FK_Actividad` ASC) VISIBLE,
  CONSTRAINT `fk_Comercial_Actividad2`
    FOREIGN KEY (`FK_Actividad`)
    REFERENCES `inspecciones_barva`.`actividad` (`PK_Codigo`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = ujis;


-- -----------------------------------------------------
-- Table `inspecciones_barva`.`contribuyente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `inspecciones_barva`.`contribuyente` ;

CREATE TABLE IF NOT EXISTS `inspecciones_barva`.`contribuyente` (
  `PK_ID` VARCHAR(45) NOT NULL,
  `Nombre` VARCHAR(45) NULL DEFAULT NULL,
  `Telefono` INT NULL DEFAULT NULL,
  `Numero_Finca` VARCHAR(45) NULL DEFAULT NULL,
  `Direccion` VARCHAR(100) NULL DEFAULT NULL,
  `Fax` VARCHAR(45) NULL DEFAULT NULL,
  `Correo` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`PK_ID`),
  INDEX `fk_Contribuyente_Usuario1_idx` (`PK_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Contribuyente_Usuario1`
    FOREIGN KEY (`PK_ID`)
    REFERENCES `inspecciones_barva`.`usuario` (`PK_ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = ujis;


-- -----------------------------------------------------
-- Table `inspecciones_barva`.`expectaculo_publico`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `inspecciones_barva`.`expectaculo_publico` ;

CREATE TABLE IF NOT EXISTS `inspecciones_barva`.`expectaculo_publico` (
  `FK_Actividad` INT NOT NULL,
  `Patente` TINYINT NOT NULL,
  `Días` VARCHAR(45) NULL DEFAULT NULL,
  `Horario` VARCHAR(45) NULL DEFAULT NULL,
  `Cumple_Regulacion_Horaria` TINYINT NULL DEFAULT NULL,
  INDEX `fk_Comercial_Actividad1_idx` (`FK_Actividad` ASC) VISIBLE,
  CONSTRAINT `fk_Comercial_Actividad1`
    FOREIGN KEY (`FK_Actividad`)
    REFERENCES `inspecciones_barva`.`actividad` (`PK_Codigo`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = ujis;


-- -----------------------------------------------------
-- Table `inspecciones_barva`.`solicitud_patente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `inspecciones_barva`.`solicitud_patente` ;

CREATE TABLE IF NOT EXISTS `inspecciones_barva`.`solicitud_patente` (
  `PK_Codigo` INT NOT NULL AUTO_INCREMENT,
  `FK_ID_Contribuyente` VARCHAR(45) NOT NULL,
  `Nombre_Representante_Legal_Contribuyente` VARCHAR(45) NULL DEFAULT NULL,
  `Cedula_Representante_Legal_Contribuyente` VARCHAR(45) NULL DEFAULT NULL,
  `Nombre_Propetario` VARCHAR(45) NULL DEFAULT NULL,
  `Cedula_Propetario` VARCHAR(45) NULL DEFAULT NULL,
  `Nombre_Representante_Legal_Propietario` VARCHAR(45) NULL DEFAULT NULL,
  `Direccion_Propietario` VARCHAR(100) NULL DEFAULT NULL,
  `Nombre_Comercial_Negocio` VARCHAR(45) NULL DEFAULT NULL,
  `Actividad` VARCHAR(45) NULL DEFAULT NULL,
  `Nombre_Persona_Autorizada` VARCHAR(45) NULL DEFAULT NULL,
  `ID_Persona_Autorizada` VARCHAR(45) NULL DEFAULT NULL,
  `Declaracion_Jurada` VARCHAR(45) NULL DEFAULT NULL,
  `Fecha` DATETIME(3) NULL DEFAULT NULL,
  `Requisitos_Articulo9_Muni_Barva` VARCHAR(45) NULL DEFAULT NULL,
  `Inscrito_CSS_Se_Encuentra_al_dia` VARCHAR(45) NULL DEFAULT NULL,
  `Inscrito_FODESAF` VARCHAR(45) NULL DEFAULT NULL,
  `Exoneracion_y_Poliza_Riesgo_de_trabajo_del_INS` VARCHAR(45) NULL DEFAULT NULL,
  `Timbre_Fiscal` VARCHAR(45) NULL DEFAULT NULL,
  `Formulario_Solicitud_Patente_Firmada` VARCHAR(45) NULL DEFAULT NULL,
  `Declaracion_Jurada_Firmada` VARCHAR(45) NULL DEFAULT NULL,
  `Al_Dia_Impuestos_Municipales` VARCHAR(45) NULL DEFAULT NULL,
  `Contrato_Arrendamiento` VARCHAR(45) NULL DEFAULT NULL,
  `Estado` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`PK_Codigo`),
  INDEX `fk_Solicitud_Patente_Contribuyente1_idx` (`FK_ID_Contribuyente` ASC) VISIBLE,
  CONSTRAINT `fk_Solicitud_Patente_Contribuyente1`
    FOREIGN KEY (`FK_ID_Contribuyente`)
    REFERENCES `inspecciones_barva`.`contribuyente` (`PK_ID`))
ENGINE = InnoDB
AUTO_INCREMENT = 13
DEFAULT CHARACTER SET = ujis;


-- -----------------------------------------------------
-- Table `inspecciones_barva`.`inspeccion_patente_nueva`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `inspecciones_barva`.`inspeccion_patente_nueva` ;

CREATE TABLE IF NOT EXISTS `inspecciones_barva`.`inspeccion_patente_nueva` (
  `PK_Codigo_Inspeccion` INT NOT NULL AUTO_INCREMENT,
  `FK_Inspector_Administrativo` VARCHAR(45) NOT NULL,
  `FK_Solicitud_Patente` INT NOT NULL,
  `Descripcion` VARCHAR(256) NULL DEFAULT NULL,
  `Fecha` DATETIME(3) NULL DEFAULT NULL,
  `Local` VARCHAR(100) NULL DEFAULT NULL,
  `Direccion` VARCHAR(256) NULL DEFAULT NULL,
  `Requisito_Local_Acorde_Actividadl` VARCHAR(2) NULL DEFAULT NULL,
  `Planta_Fisica` VARCHAR(2) NULL DEFAULT NULL,
  `Senalizacion` VARCHAR(2) NULL DEFAULT NULL,
  `Luces_Emergencias` VARCHAR(2) NULL DEFAULT NULL,
  `Extintor` VARCHAR(2) NULL DEFAULT NULL,
  `Salida_Emergencia` VARCHAR(2) NULL DEFAULT NULL,
  PRIMARY KEY (`PK_Codigo_Inspeccion`),
  INDEX `fk_Inspeccion_Patente_Administrativo1_idx` (`FK_Inspector_Administrativo` ASC) VISIBLE,
  INDEX `fk_Inspeccion_Patente_Nueva_Solicitud_Patente1_idx` (`FK_Solicitud_Patente` ASC) VISIBLE,
  CONSTRAINT `fk_Inspeccion_Patente_Administrativo1`
    FOREIGN KEY (`FK_Inspector_Administrativo`)
    REFERENCES `inspecciones_barva`.`administrativo` (`PK_ID`),
  CONSTRAINT `fk_Inspeccion_Patente_Nueva_Solicitud_Patente1`
    FOREIGN KEY (`FK_Solicitud_Patente`)
    REFERENCES `inspecciones_barva`.`solicitud_patente` (`PK_Codigo`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = ujis;


-- -----------------------------------------------------
-- Table `inspecciones_barva`.`testigo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `inspecciones_barva`.`testigo` ;

CREATE TABLE IF NOT EXISTS `inspecciones_barva`.`testigo` (
  `PK_ID` INT NOT NULL,
  `Nombre_Completo` VARCHAR(100) NULL DEFAULT NULL,
  `Telefono` INT NULL DEFAULT NULL,
  `Correo` VARCHAR(45) NULL DEFAULT NULL,
  `firma` VARCHAR(256) NULL DEFAULT NULL,
  PRIMARY KEY (`PK_ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = ujis;


-- -----------------------------------------------------
-- Table `inspecciones_barva`.`inspeccion_ocular`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `inspecciones_barva`.`inspeccion_ocular` ;

CREATE TABLE IF NOT EXISTS `inspecciones_barva`.`inspeccion_ocular` (
  `PK_Codigo_Inspeccion` INT NOT NULL AUTO_INCREMENT,
  `FK_Inspeccion_Patente_Nueva` INT NOT NULL,
  `Lugar_Visita` VARCHAR(256) NULL DEFAULT NULL,
  `Fecha` DATETIME NOT NULL,
  `Diligencia` VARCHAR(256) NULL DEFAULT NULL,
  `Resultado` VARCHAR(256) NULL DEFAULT NULL,
  `FK_Testigo1` INT NOT NULL,
  `FK_Testigo2` INT NOT NULL,
  PRIMARY KEY (`PK_Codigo_Inspeccion`),
  INDEX `fk_Inspeccion_Ocular_Inspeccion_Patente_Nueva1_idx` (`FK_Inspeccion_Patente_Nueva` ASC) VISIBLE,
  INDEX `fk_Inspeccion_Ocular_Testigo1_idx` (`FK_Testigo1` ASC) VISIBLE,
  INDEX `fk_Inspeccion_Ocular_Testigo2_idx` (`FK_Testigo2` ASC) VISIBLE,
  CONSTRAINT `fk_Inspeccion_Ocular_Inspeccion_Patente_Nueva1`
    FOREIGN KEY (`FK_Inspeccion_Patente_Nueva`)
    REFERENCES `inspecciones_barva`.`inspeccion_patente_nueva` (`PK_Codigo_Inspeccion`),
  CONSTRAINT `fk_Inspeccion_Ocular_Testigo1`
    FOREIGN KEY (`FK_Testigo1`)
    REFERENCES `inspecciones_barva`.`testigo` (`PK_ID`),
  CONSTRAINT `fk_Inspeccion_Ocular_Testigo2`
    FOREIGN KEY (`FK_Testigo2`)
    REFERENCES `inspecciones_barva`.`testigo` (`PK_ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = ujis;


-- -----------------------------------------------------
-- Table `inspecciones_barva`.`notificacion_inspeccion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `inspecciones_barva`.`notificacion_inspeccion` ;

CREATE TABLE IF NOT EXISTS `inspecciones_barva`.`notificacion_inspeccion` (
  `PK_Codigo` INT NOT NULL AUTO_INCREMENT,
  `FK_Inspeccion_Ocular` INT NOT NULL,
  `Resultado` VARCHAR(45) NULL DEFAULT NULL,
  `FK_Actividad` INT NOT NULL,
  `Fecha` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`PK_Codigo`),
  INDEX `fk_Notificacion_Inspeccion_Inspeccion_Ocular1_idx` (`FK_Inspeccion_Ocular` ASC) VISIBLE,
  INDEX `fk_Notificacion_Inspeccion_Actividad1_idx` (`FK_Actividad` ASC) VISIBLE,
  CONSTRAINT `fk_Notificacion_Inspeccion_Actividad1`
    FOREIGN KEY (`FK_Actividad`)
    REFERENCES `inspecciones_barva`.`actividad` (`PK_Codigo`),
  CONSTRAINT `fk_Notificacion_Inspeccion_Inspeccion_Ocular1`
    FOREIGN KEY (`FK_Inspeccion_Ocular`)
    REFERENCES `inspecciones_barva`.`inspeccion_ocular` (`PK_Codigo_Inspeccion`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = ujis;


-- -----------------------------------------------------
-- Table `inspecciones_barva`.`patente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `inspecciones_barva`.`patente` ;

CREATE TABLE IF NOT EXISTS `inspecciones_barva`.`patente` (
  `FK_Codigo` INT NOT NULL AUTO_INCREMENT,
  `FK_Contribuyente` VARCHAR(45) NOT NULL,
  `FK_Actividad` INT NOT NULL,
  `Descripcion` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`FK_Codigo`),
  INDEX `fk_Patente_Contribuyente1_idx` (`FK_Contribuyente` ASC) VISIBLE,
  INDEX `fk_Patente_Actividad1_idx` (`FK_Actividad` ASC) VISIBLE,
  CONSTRAINT `fk_Patente_Actividad1`
    FOREIGN KEY (`FK_Actividad`)
    REFERENCES `inspecciones_barva`.`actividad` (`PK_Codigo`),
  CONSTRAINT `fk_Patente_Contribuyente1`
    FOREIGN KEY (`FK_Contribuyente`)
    REFERENCES `inspecciones_barva`.`contribuyente` (`PK_ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = ujis;


-- -----------------------------------------------------
-- Table `inspecciones_barva`.`venta_licor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `inspecciones_barva`.`venta_licor` ;

CREATE TABLE IF NOT EXISTS `inspecciones_barva`.`venta_licor` (
  `FK_Actividad` INT NOT NULL,
  `Nombre_Local` VARCHAR(45) NULL DEFAULT NULL,
  `Patente` VARCHAR(45) NULL DEFAULT NULL,
  `Numero_Patente_Licor` VARCHAR(45) NULL DEFAULT NULL,
  `Patente_Licor` VARCHAR(45) NULL DEFAULT NULL,
  INDEX `fk_Comercial_Actividad2_idx` (`FK_Actividad` ASC) VISIBLE,
  CONSTRAINT `fk_Comercial_Actividad20`
    FOREIGN KEY (`FK_Actividad`)
    REFERENCES `inspecciones_barva`.`actividad` (`PK_Codigo`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = ujis;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
